### ISSUE TITLE
Periodic Pipeline Failures under High Load

### ISSUE THREAD

**Issue by ncbrown1** [Azure/logstash-output-kusto#10]
I'm running a few thousand messages per second through a logstash pipeline using this plugin, and after a few minutes I start seeing the following message in my logs:

```
[2019-02-05T11:38:41,174][ERROR][logstash.outputs.kusto   ] Uploading failed, retrying.{:exception=>Errno::ENOENT, :message=>"No such file or directory - No such file or directory - /export/content/data/in-logstash/i001/tmp/kusto/2019-02-05-15-22.txt.kusto", path=>"/export/content/data/in-logstash/i001/tmp/kusto/2019-02-05-15-22.txt.kusto", :backtrace=>["org/jruby/RubyFileTest.java:239:in `size'", "/export/content/lid/apps/in-logstash/i001/logstash/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/logstash-output-kusto-0.2.0/lib/logstash/outputs/kusto/ingestor.rb:76:in `upload'", "/export/content/lid/apps/in-logstash/i001/logstash/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/logstash-output-kusto-0.2.0/lib/logstash/outputs/kusto/ingestor.rb:68:in `upload_async'", "org/jruby/RubyProc.java:281:in `call'", "/export/content/lid/apps/in-logstash/i001/logstash/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/concurrent-ruby-1.0.5-java/lib/concurrent/executor/java_executor_service.rb:94:in `run'", "Concurrent$$JavaExecutorService$$Job_2081311098.gen:13:in `run'"]}
```

I have a feeling that this may be a race condition where the file has already been flushed, but a logstash worker keeps trying to flush the (non-existent) file. My resolution is to just restart the pipeline and let the recovery mechanism do its thing.

**Comment by tamirkamara** [comment]
Is this easy to replicate, like happening fairly quickly and routinely? 
Would it possible for you to increase logging level for the plugin and then share the logstash logs that include those extra debug messages (I can followup with instructions)?

**Comment by ncbrown1** [comment]
So this happened as I was "catching up" on a day's worth of data from two different data sources. This may be due to the fact that I was using the following config:
```
kusto {
      path => "/tmp/kusto/%{+YYYY-MM-dd-HH-mm}.txt"
      ...
}
```
I switched it to the following and the issue did not happen again:
```

kusto {
      path => "/tmp/kusto/%{type}-%{+YYYY-MM-dd-HH-mm}.txt"
      ...
}
```

I have a feeling that this was due to the fact that multiple threads were writing to the same file (from different sources) and one of them decided to flush without the other thread noticing.

**Comment by reschex** [comment]
Hi guys
I'm running into this as well.
I've got a kafka input with a single thread and then multiple output sections to kusto, depending on a value in the input data:
```       if [<key>] == "<value>" {
        kusto {
          ...
          path => "/kusto-ingest/%{+YYYY-MM-dd-HH-mm}_<value>"
          ingest_url => "${KUSTO_INGEST_URL}"
          ...
          delete_temp_files => "true"
        }
      }```

I wouldn't call whats happening particularly high load about ~30EPS. It did take a while (~6+ hours) for the issue to start too).

Ideally I'm trying to understand how to recover from this - as I'm using a stateful set in k8s, when I kill my logstash pod it will restart with a fresh pod, but the PVC won't delete - so when logstash starts up it immidiatly tries to find the old fieles again - which have since been uploaded by the plugin going over old files from previous runs. so the errors continue forever. assuming they are stored somewhere in the guts of the logstash queue on disk?

Also trying to understand why it is happening and if I can do anything about it.

thanks!

Roland

**Comment by i3arnon** [comment]
@reschex It seems like this happens when multiple outputs use the same directory. Is it possible to use different directories for each output?

@ncbrown1 Was that also the case for you? Or did you have a single output?

**Comment by reschex** [comment]
@i3arnon - I will give it a try - I'm assuming the plugin doesn't create directories when they don't exist? Will have to see how I can template all of this in helm.

I kinda thought that having the different outputs write to different temp files will prevent different threads fighting over the same file handle?

**Comment by reschex** [comment]
just realised what you mean - do the different output try to upload just all *.kusto files from the directory? In which case different threads would compete for the upload with one thread succeeding before another one causing the 2nd one starting to spew errors for files it was going to upload but no longer can because the first thread did..

**Comment by i3arnon** [comment]
@reschex it depends on the template configured in `path`.
If it's in the same directory and the files are only differentiated by timestamp it's bound to collide at some point.
It's just safer to have the outputs use exclusive directories.

**Comment by reschex** [comment]
@i3arnon I've found that the plugin create dirs that don't exist which is great and makes things a lot easier. I've updated my config to be:

`     if [<key>] == "<value>" {
        kusto {
          ...
          path => "/kusto-ingest/<value>/%{+YYYY-MM-dd-HH-mm}_<value>"
          ...
        }
      }`

Currently running through the build pipeline - when it's made its way into the long running namespace, I will keep an eye on it and update here later.

**Comment by ncbrown1** [comment]
I changed my configuration to use a different directory for each output (similar to what @reschex showed above), but I still find that this issue occurs after a few days of running the pipeline. Once this happens, the same error log message will keep getting emitted until the pipeline shuts down.

**Comment by reschex** [comment]
@ncbrown1 - we've observed the pipeline stopping to process data into kusto eventually when this issue occurs - does the same happen for you?
Also wondering.. are you using logstash persistent queues? and what storage are you using for the kusto tmp files?

Wondering if its related as pesistent queues and kusto plugin together would be quite IO heavy, espsecially when writing to an azurefile pvc like we do. I'm going to change our pvc to block store and disable persistent queues to see if that makes a difference.

**Comment by ncbrown1** [comment]
I've noticed that when I use multiple kusto outputs, data will nondeterministically get sent to one of the destination destination configurations. This is really really bad, given that different databases can have different access restrictions. So data can be leaked to someone who potentially shouldn't be seeing that data.

**Comment by ncbrown1** [comment]
found the reason I think… https://github.com/Azure/logstash-output-kusto/blob/master/lib/logstash/outputs/kusto.rb#L360

Basically, the plugin looks for the first non-fieldref part of the destination path. which may look like this:
```
path => "/export/data/logstash/kusto/%{type}/%{type}-%{+YYYY-MM-dd-HH-mm}.txt"
```
Since all outputs are sharing `/export/data/logstash/kusto/` as the base directory, all outputs find the same files to upload to their corresponding destination. So if we change this config to something like this:
```
path => "/export/data/logstash/kusto/app1-log_event/%{type}-%{+YYYY-MM-dd-HH-mm}.txt"
```
There should be no data routing/duplication issues I referenced in my previous comment.

**Comment by ncbrown1** [comment]
I've also made a local edit after this line: https://github.com/Azure/logstash-output-kusto/blob/e76686e9cb2dccc909a985e8b0edcb1fb3f96013/lib/logstash/outputs/kusto/ingestor.rb#L100
```
    rescue Errno::ENOENT => e
      @logger.error("File doesn't exist! Unrecoverable error.", exception: e.class, message: e.message, path: path, backtrace: e.backtrace)
```
This is similar in intention to the `Java::JavaNioFile::NoSuchFileException`, so I felt that it belonged here. If the file doesn't exist, it shouldn't get retried, eh? My configuration has been much more stable since this local change.

**Comment by reschex** [comment]
@ncbrown1 good spot on the recover_past_files method - this is basically when the plugin starts and tries to find previously left behind .kusto files and uploads them.
Now I'll caveat the next bit with, I've not had a long look and I don't know ruby very well (at all) - but to me it looks like even changing the config to 
```
path => "/export/data/logstash/kusto/app1-log_event/%{type}-%{+YYYY-MM-dd-HH-mm}.txt"
```
won't prevent the different outputs form randomly uploading stuff on startup.

The way I understand it, the 'path' is normally generated based on the event, which makes sense with dynamic config like you and I have - but the recover_past_files method has no input of any kind. As I read it, it literally goes and finds all files called *.kusto in the non-dynamic part of the filepath and puts them to kusto_send_file, which is `@ingestor.upload_async(file_path, delete_temp_files)`, so depending on which output grabs a file first, it will upload it to whatever database is configured in that output, regardless of what previously dynamic part of the filename is configured - which I can only agree is really really bad.

**Comment by reschex** [comment]
We have time set aside next sprint to dig a bit more into this - hopefully we'll be able to apply your local edit our end too - although whilst I see how it will prevent the thread hanging, I still don't see how the error occurs to start with (outside the recover_past_files method, which is only called at the end of `register`, i.e. on plugin startup) - and looking at the comments around that section of code, it looks like it was originally designed to hang on that point on purpose - although I agree, I'd rather have the behaviour of a single error and move on, opposed to try and find a nonexisting file forever.

**Comment by i3arnon** [comment]
Hey @reschex, @ncbrown1,
We've just released a new version of the plugin which should be more resilient:
https://rubygems.org/gems/logstash-output-kusto/versions/0.3.0

Could you upgrade and share whether you're still having issue?

**Comment by ncbrown1** [comment]
Hey @i3arnon I've recently upgraded and am no longer facing the same issues I did before. The pipeline seems much more resilient now! Thanks.

**Comment by i3arnon** [comment]
Then I'll close the issue. Please open a new one if you're having issues...
