### ISSUE TITLE
Use Maven Kusto libs when available

### ISSUE THREAD

**Issue by tamirkamara** [Azure/logstash-output-kusto#2]
Currently the plugin uses an embedded jar for the Kusto sdk. We should move that to a maven reference when it will be published there.

**Comment by reschex** [comment]
Hi Tamir 
can you provide some instructions on how to build a jar from https://github.com/Azure/azure-kusto-java that works with the logstash plugin? The artifacts created by mvn package for example fail immidiately when I try to start logstash afer rebuilding and installing the logstash plugin.

Thanks!

**Comment by vladikbr** [comment]
Resolved
