### ISSUE TITLE
Add client certificate support to plugin

### ISSUE THREAD

**Issue by gbordier** [Azure/logstash-output-kusto#50]
Given the underlying kusto java sdk (https://github.com/Azure/azure-kusto-java/blob/master/data/src/test/java/com/microsoft/azure/kusto/data/ConnectionStringBuilderTest.java#L64 ) does support it, it would be wonderful to be handle at least certificate based authentication to kusto or even better Azure AD Managed Identity for cases where Logstash runs on an Arc-enabled workload or an azure VM.

**Comment by ag-ramachandran** [comment]
Hello @gbordier , Thanks for bringing this up. We're working on a subsequent release where we intend to support Certificate and Managed Identity support. We're targeting may be 2.0.1 release in 4 weeks or so.

**Comment by ag-ramachandran** [comment]
Hello @gbordier

Quick update : 
Will try and provide ManagedIdentity provider as this is not very difficult feature to accomplish. The idea would be to pass managedIdentityId in the logstash config and then use that in the code for ingestion.

Will try and provide a release for this early next week (Monday or Tuesday once we get the reviews done)

**Comment by ag-ramachandran** [comment]
Update: Just started to test this feature E2E. Will plan a release this week

**Comment by ag-ramachandran** [comment]
Hello @gbordier 

Added support for managed identity in the Plugin
