### ISSUE TITLE
Intermittent Java::JavaUtil::ConcurrentModificationException errors

### ISSUE THREAD

**Issue by cryptondav** [Azure/logstash-output-kusto#69]
I encounter intermittent Java::JavaUtil::ConcurrentModificationException errors during data ingestion.

`Java::JavaUtil::ConcurrentModificationException, :message=>"", :path=>"/tmp/kusto/adx-unparsed/2024-03-07-10-02-37.txt.secopsadx.Logstash_ParseError", :backtrace=>["java.util.ArrayDeque.nonNullElementAt(java/util/ArrayDeque.java:270)", "java.util.ArrayDeque$DeqIterator.next(java/util/ArrayDeque.java:700)", "com.microsoft.azure.kusto.ingest.resources.RankedStorageAccount.getRank(com/microsoft/azure/kusto/ingest/resources/RankedStorageAccount.java:86)", "com.microsoft.azure.kusto.ingest.resources.RankedStorageAccountSet.getRankedShuffledAccounts(com/microsoft/azure/kusto/ingest/resources/RankedStorageAccountSet.java:79)", "com.microsoft.azure.kusto.ingest.ResourceManager.getShuffledContainers(com/microsoft/azure/kusto/ingest/ResourceManager.java:134)", "com.microsoft.azure.kusto.ingest.ResourceAlgorithms.uploadLocalFileWithRetries(com/microsoft/azure/kusto/ingest/ResourceAlgorithms.java:94)", "com.microsoft.azure.kusto.ingest.QueuedIngestClientImpl.ingestFromFileImpl(com/microsoft/azure/kusto/ingest/QueuedIngestClientImpl.java:173)", "com.microsoft.azure.kusto.ingest.IngestClientBase.lambda$ingestFromFile$0(com/microsoft/azure/kusto/ingest/IngestClientBase.java:61)", "com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(com/microsoft/azure/kusto/data/instrumentation/MonitoredActivity.java:33)", "com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(com/microsoft/azure/kusto/data/instrumentation/MonitoredActivity.java:26)", "com.microsoft.azure.kusto.ingest.IngestClientBase.ingestFromFile(com/microsoft/azure/kusto/ingest/IngestClientBase.java:60)", "jdk.internal.reflect.GeneratedMethodAccessor63.invoke(jdk/internal/reflect/GeneratedMethodAccessor63)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:330)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:188)", "usr.share.logstash.vendor.bundle.jruby.$3_dot_1_dot_0.gems.logstash_minus_output_minus_kusto_minus_2_dot_0_dot_4_minus_java.lib.logstash.outputs.kusto.ingestor.upload(/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-kusto-2.0.4-java/lib/logstash/outputs/kusto/ingestor.rb:145)", "usr.share.logstash.vendor.bundle.jruby.$3_dot_1_dot_0.gems.logstash_minus_output_minus_kusto_minus_2_dot_0_dot_4_minus_java.lib.logstash.outputs.kusto.ingestor.upload_async(/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-output-kusto-2.0.4-java/lib/logstash/outputs/kusto/ingestor.rb:118)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:315)", "org.jruby.RubyProc$INVOKER$i$call.call(org/jruby/RubyProc$INVOKER$i$call.gen)", "usr.share.logstash.vendor.bundle.jruby.$3_dot_1_dot_0.gems.concurrent_minus_ruby_minus_1_dot_1_dot_9.lib.concurrent_minus_ruby.concurrent.executor.java_executor_service.run(/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/java_executor_service.rb:79)", "java.util.concurrent.Executors$RunnableAdapter.call(java/util/concurrent/Executors.java:539)", "java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:264)", "java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1136)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:635)", "java.lang.Thread.run(java/lang/Thread.java:840)"]}`

This exception seems to stem from a known issue in the Azure Kusto Java SDK, which has been addressed in the recent v5.0.5 release [Issue #352](https://github.com/Azure/azure-kusto-java/issues/352) and the release notes [here](https://github.com/Azure/azure-kusto-java/releases/tag/v5.0.5).

Currently, the latest logstash-output-kusto plugin relies on an older version of this SDK (v5.0.3), which is affected by this bug.

**Steps to Reproduce:**

1. Configure Logstash with the logstash-output-kusto plugin to ingest data into Azure Data Explorer.
2. Observe the Java::JavaUtil::ConcurrentModificationException occurring intermittently during the ingestion process.

**Additional Context:**

This issue was specifically identified and patched in the Azure Kusto Java SDK. Updating dependencies is a critical step to leverage these improvements.

**Potential Workaround**
A temporary workaround involved locally updating the [kusto-ingest-5.0.5.jar](https://github.com/Azure/azure-kusto-java/releases/download/v5.0.5/kusto-ingest-5.0.5.jar) and [kusto-data-5.0.5.jar](https://github.com/Azure/azure-kusto-java/releases/download/v5.0.5/kusto-data-5.0.5.jar)

For reference, this is the kusto output config

`input {
  pipeline {
    address => "output-adx-unparsed"
  }
}

filter {
    # Prune the event to include only specified fields.
    prune {
        whitelist_names => ["timestamp", "message"]
      }
}

output {
  kusto {
    path => "/tmp/kusto/adx-unparsed/%{+YYYY-MM-dd-HH-mm-ss}.txt"
    ingest_url => "*******"
    app_id => "******"
    app_key => "****"
    app_tenant => "*****"
	flush_interval => 30
    database => "*****"
    table => "Logstash_ParseError"
    json_mapping => "basicmsg"
  }
}`

**Comment by cryptondav** [comment]
Replacing the [kusto-ingest-5.0.5.jar](https://github.com/Azure/azure-kusto-java/releases/download/v5.0.5/kusto-ingest-5.0.5.jar) and [kusto-data-5.0.5.jar](https://github.com/Azure/azure-kusto-java/releases/download/v5.0.5/kusto-data-5.0.5.jar) libraries seems to have fixed the issue.

I believe the only change required for a fix is in [build.gradle](https://github.com/Azure/logstash-output-kusto/blob/da1a4486feeac022ddbb59e36919b810aa09a879/build.gradle#L39).

**Comment by ag-ramachandran** [comment]
hello @cryptondav : Have a PR out for this. Tested it a few times and it seemed alright. Will try and make a release

https://github.com/Azure/logstash-output-kusto/pull/70

Regards
Ram
