### ISSUE TITLE
No compression for uploading data

### ISSUE THREAD

**Issue by JPvRiel** [Azure/logstash-output-kusto#72]
As per [https://learn.microsoft.com/en-us/azure/data-explorer/ingestion-supported-formats](https://learn.microsoft.com/en-us/azure/data-explorer/ingestion-supported-formats "https://learn.microsoft.com/en-us/azure/data-explorer/ingestion-supported-formats"), it's possible to reduce network IO and save bandwidth by compressing the files before upload. `.gzip` or `.zip` formats are supported by ADX clusters but this plugin has not implemented any compression features?

I reviewed <https://github.com/Azure/logstash-output-kusto/blob/44928725bec337b5307c5a828c5ab916ad84762f/lib/logstash/outputs/kusto/ingestor.rb#L125>, but I was unable to see any evidence that compression was implemented.

**Comment by JPvRiel** [comment]
A few more notes. I saw this plugin is written in ruby, but wraps the Java SDK for ADX.

This was the upload ingestion func call:

```ruby
@kusto_client.ingestFromFile(file_source_info, @ingestion_properties)
```

And the client is not the streaming client? Just a normal client?

```ruby
kusto_java.ingest.IngestClientFactory.createClient(kusto_connection_string)
```

And the ingestion properties are:

```ruby
@ingestion_properties = kusto_java.ingest.IngestionProperties.new(database, table)
```

Again, no obvious options related to compression found here.

I also wondered if, implicitly, the underlying java SDK does do compression?

As per <https://github.com/Azure/azure-kusto-java>, in this project it's clear gzip output or input streams are supported and that there is a streaming interface to post HTTP requests to, which in addition, the HTTP request can be gzip encoded.

However, I wasn't able to follow the complexity of the Java code to determine if, by default, the .uploadFromFile might implicitly be using gzip encoding.

So if, by default, this output plugin does compress output, that feature needs to be documented clearly. Alternatively, compression options should be explicitly surfaced in the logstash config to allow for ensuring compression is setup.

**Comment by ag-ramachandran** [comment]
Hello @JPvRiel , Thanks for the questions

1. The default is to always compress, here is an example. Made a deliberate failure to see the blob that failed, and sure enough you see the payload compressed. That is the implicit SDK behavior (it is opaque to the user as it is specifically for ingestion internally and that is why compression is not a supported option). The ingestion property is to prevent double compression internally  ![image](https://github.com/Azure/logstash-output-kusto/assets/106139410/246d0890-57ea-4d53-9b7d-823d8f221a3f)
2. Streaming has implications on how much data can be ingested in one go. The most ideal streaming ingest quantum is 4MB blocks , so the logic to split has to be incorporated too. For large log movers like Logstash, it makes it a lot more harder to do something like this in the logic
3. There is no Ruby SDK for Kusto, unfortunately the Ruby SDK for Azure is in its deprecation cycle. So we had to use the JRuby flavor to use the Java SDK 

Note : closing the issue, hopefully I touched upon all points

**Comment by JPvRiel** [comment]
@ag-ramachandran , thanks for a speedy reply. I'm still curious because when, in our case, logstash had upload errors, I examined the on disc files before they were uploaded, and they were not compressed. E.g.

```console
# tail -n1 2024-06-27-08-05-03.txt.logs.syslog
{"msg":"0|Check Point|VPN-1 & FireWall-1|Check Point|Log|domain-udp|Unknown|act=Accept deviceDirection=0 rt=1719475174000 spt=51878 dpt=53 cs2Label=Rule Name layer_name=*** Security layer_uuid=6b5a99e1-2674-4191-babf-254ff3023277 match_id=349 parent_rule=0 rule_action=Accept rule_uid=89555d67-e2bc-4227-85e5-9029778df1b7 conn_direction=Internal ifname=*** logid=0 loguid={0xb39c540a,0x65e84103,0x7de18f4d,0x892bcdf5} origin=10.*.*.* originsicname=CN\\=***,O\\=***..y8ps35 sequencenum=405 version=5 dst=10.*.*.* log_delay=1719475174 product=VPN-1 & FireWall-1 proto=17 service_id=domain-udp src=10.*.*.*","timestamp":"2024-06-27T11:05:03.898448+03:00","procid":"-","syslogseverity-text":"notice","syslogfacility":1,"syslogtag":"CEF:","syslogfacility-text":"user","hostname":"10.*.*.*","app-name":"CEF","@version":"1","msgid":"-","host":"localhost","syslogseverity":5,"@timestamp":"2024-06-27T08:05:03.913Z","@meta":{"header":"invalid","rawmsg":"CEF:0|Check Point|VPN-1 & FireWall-1|Check Point|Log|domain-udp|Unknown|act=Accept deviceDirection=0 rt=1719475174000 spt=51878 dpt=53 cs2Label=Rule Name layer_name=*** Security layer_uuid=6b5a99e1-2674-4191-babf-254ff3023277 match_id=349 parent_rule=0 rule_action=Accept rule_uid=89555d67-e2bc-4227-85e5-9029778df1b7 conn_direction=Internal ifname=*** logid=0 loguid={0xb39c540a,0x65e84103,0x7de18f4d,0x892bcdf5} origin=10.*.*.* originsicname=CN\\=***,O\\=***..y8ps35 sequencenum=405 version=5 dst=10.*.*.* log_delay=1719475174 product=VPN-1 & FireWall-1 proto=17 service_id=domain-udp src=10.*.*.*","timegenerated":"2024-06-27T11:05:03.898448+03:00","fromhost-ip":"10.*.*.*","output":"CEF","fromhost":"10.*.*.*","inputname":"imptcp601"},"port":48364}
```

So on the local storage logstash isn't compressing the files before upload. But you're saying that the Java SDK somehow reads these uncompressed files and gzip compresses them when uploading them as storage blobs?

I also checked my side. I see the blob has a compression extension.

![image](https://github.com/Azure/logstash-output-kusto/assets/9722317/bebdd243-6482-4e90-95a2-4a53d9841562)

Perhaps it's best to update the readme for this output plugin to explicitly state the underlying Java SDK transparently compresses the batched output files when uploading them as storage blobs.

**Comment by ag-ramachandran** [comment]
Hello @JPvRiel , Local files are uncompressed so that they can be appended to. When a finalized and flushed it is compressed
