### ISSUE TITLE
Streaming ingestion supported ?

### ISSUE THREAD

**Issue by seb2020** [Azure/logstash-output-kusto#75]
Hi,

Does the plugin support streaming ingestion? If no, is this planned to add this feature ? 

Thanks

**Comment by seb2020** [comment]
Hi,

We are sending log from our internal application to logstash and then to ADX for debugging purpose. Now, we can see 3 to 5 minutes of delay for reading log in the ADX. It's inconvenient for developers to have to wait so long to read the logs.

Example : we run a container and the application is run. After some test, there is an error log send to the logstash. The developer should wait to see the logs to correct the issue. Then, he re-run the container, retest and then wait some minutes to read the logs.

And we don't want to manage an internal elastic stack or something similar to read logs has we have already ADX for log.

**Comment by seb2020** [comment]
I cannot do the configuration because of :

- Error during execution of a policy operation: MaximumBatchingTimeSpan should be greater than or equal to 00:00:10
- Error during execution of a policy operation: MaximumRawDataSizeMB should be greater than or equal to 100

**Comment by ag-ramachandran** [comment]
Sorry for not being clear, substituting with the min values on the document. Can you try with this please

.alter table policy ingestionbatching

{
    "MaximumBatchingTimeSpan" : "00:00:10",
    "MaximumNumberOfItems" : 1,
    "MaximumRawDataSizeMB" : 100
}

**Comment by ag-ramachandran** [comment]
Sorry for the delay in getting back @seb2020 , there are a couple of challenges with respect to streaming

> Data packets in streaming have to be split into 4 MB chunks, which is additional work needed
> Not all clusters are streaming enabled (though this can be changed)

We are working on a feature for having this done, it is may be a couple of months out at this point ( will try and prioritize it )
